import './style.css';
import { createClient } from '@supabase/supabase-js';
import { PRINT_POLICY, PRINT_EXTRAS_CLP, QUALITY_ADJUSTMENT_CLP, checkResolution, orderTotal } from './print-check.js';
import { communes, provinces } from '@clregions/data/array';
const icons={arrow:'↗',spark:'✳',close:'×'};
const CUSTOMER_DETAILS_KEY='droska-customer-details';
const DRAFT_KEY='droska-shirt-draft';
const SAVED_DETAILS_TTL=15*24*60*60*1000;
const DESIGN_DATABASE='droska-designs';
const DESIGN_STORE='uploads';
function loadSavedData(key){try{const value=JSON.parse(localStorage.getItem(key)||'{}');if(!value||typeof value!=='object'||typeof value.expiresAt!=='number'||value.expiresAt<=Date.now()){localStorage.removeItem(key);return {}}return value}catch{return {}}}
function saveForFifteenDays(key,value){try{localStorage.setItem(key,JSON.stringify({...value,expiresAt:Date.now()+SAVED_DETAILS_TTL}))}catch{}}
function openDesignDatabase(){return new Promise((resolve,reject)=>{if(!('indexedDB'in window))return reject(new Error('Almacenamiento de archivos no disponible'));const request=indexedDB.open(DESIGN_DATABASE,1);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains(DESIGN_STORE))request.result.createObjectStore(DESIGN_STORE,{keyPath:'side'})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function saveDesignFile(side,file){const database=await openDesignDatabase();await new Promise((resolve,reject)=>{const transaction=database.transaction(DESIGN_STORE,'readwrite');transaction.objectStore(DESIGN_STORE).put({side,file,expiresAt:Date.now()+SAVED_DETAILS_TTL});transaction.oncomplete=resolve;transaction.onerror=()=>reject(transaction.error)});database.close()}
async function removeSavedDesignFile(side){const database=await openDesignDatabase();await new Promise((resolve,reject)=>{const transaction=database.transaction(DESIGN_STORE,'readwrite');transaction.objectStore(DESIGN_STORE).delete(side);transaction.oncomplete=resolve;transaction.onerror=()=>reject(transaction.error)});database.close()}
async function savedDesignFiles(){const database=await openDesignDatabase();const files=await new Promise((resolve,reject)=>{const request=database.transaction(DESIGN_STORE).objectStore(DESIGN_STORE).getAll();request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});database.close();return files}
const savedCustomerDetails=loadSavedData(CUSTOMER_DETAILS_KEY);
const savedDraftDetails=loadSavedData(DRAFT_KEY);
const savedFullName=savedCustomerDetails.name||'';
const savedNameParts=savedFullName.trim().split(/\s+/).filter(Boolean);
const state={mode:'ready',kind:'basic',size:'M',color:'#ffffff',image:'/laika.png',images:{front:'',back:''},files:{front:'',back:''},references:[],uploaded:false,isDefault:true,file:'',step:1,assessment:null,assessments:{front:null,back:null},printSide:'front',printSides:['front'],printScale:1,checking:false,checkingSide:'',artworkTone:'',qualityAccepted:false,qualityReview:false,email:savedCustomerDetails.email||savedDraftDetails.email||'',firstName:savedCustomerDetails.firstName||savedDraftDetails.firstName||savedNameParts[0]||'',lastName:savedCustomerDetails.lastName||savedDraftDetails.lastName||savedNameParts.slice(1).join(' '),name:savedFullName,phone:savedCustomerDetails.phone||savedDraftDetails.phone||'',region:savedCustomerDetails.region||savedDraftDetails.region||'',address:savedCustomerDetails.address||savedDraftDetails.address||'',addressExtra:savedCustomerDetails.addressExtra||savedDraftDetails.addressExtra||'',commune:savedCustomerDetails.commune||savedDraftDetails.commune||'',deliveryNotes:savedCustomerDetails.deliveryNotes||savedDraftDetails.deliveryNotes||'',fulfillment:'delivery',editingContact:false,checkoutReady:false};
function syncFullName(){state.name=[state.firstName,state.lastName].filter(Boolean).join(' ')}
function storeCustomerDetails(){syncFullName();saveForFifteenDays(CUSTOMER_DETAILS_KEY,{email:state.email,firstName:state.firstName,lastName:state.lastName,name:state.name,phone:state.phone,region:state.region,commune:state.commune,address:state.address,addressExtra:state.addressExtra,deliveryNotes:state.deliveryNotes})}
const garmentSizes=['XS','S','M','L','XL','XXL'];
const products={basic:{name:'Básica',price:14990,sizes:garmentSizes},over:{name:'Over',price:21990,sizes:garmentSizes},kids:{name:'Kid',price:8990,sizes:garmentSizes}};
const chileRegions=['Arica y Parinacota','Tarapacá','Antofagasta','Atacama','Coquimbo','Valparaíso','Metropolitana de Santiago','O’Higgins','Maule','Ñuble','Biobío','La Araucanía','Los Ríos','Los Lagos','Aysén','Magallanes'];
const chileRegionIds={'Arica y Parinacota':'15','Tarapacá':'01','Antofagasta':'02','Atacama':'03','Coquimbo':'04','Valparaíso':'05','Metropolitana de Santiago':'13','O’Higgins':'06','Maule':'07','Ñuble':'16','Biobío':'08','La Araucanía':'09','Los Ríos':'14','Los Lagos':'10','Aysén':'11','Magallanes':'12'};
const samePlace=(a,b)=>String(a).localeCompare(String(b),'es',{sensitivity:'base'})===0;
function communesForRegion(regionName){const matchedRegion=chileRegions.find(region=>samePlace(region,regionName));const regionId=chileRegionIds[matchedRegion];if(!regionId)return communes.map(commune=>commune.name);const provinceIds=new Set(provinces.filter(province=>province.regionId===regionId).map(province=>province.id));return communes.filter(commune=>provinceIds.has(commune.provinceId)).map(commune=>commune.name)}
const money=n=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(n);
const fixedChileHolidays=new Set(['01-01','05-01','05-21','06-21','06-29','07-16','08-15','09-18','09-19','10-12','10-31','11-01','12-08','12-25']);
function easterSunday(year){const a=year%19,b=Math.floor(year/100),c=year%100,d=Math.floor(b/4),e=b%4,f=Math.floor((b+8)/25),g=Math.floor((b-f+1)/3),h=(19*a+b-d-g+15)%30,i=Math.floor(c/4),k=c%4,l=(32+2*e+2*i-h-k)%7,m=Math.floor((a+11*h+22*l)/451),month=Math.floor((h+l-7*m+114)/31),day=(h+l-7*m+114)%31+1;return new Date(year,month-1,day)}
function isChileHoliday(date){const key=`${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;if(fixedChileHolidays.has(key))return true;const easter=easterSunday(date.getFullYear()),difference=Math.round((new Date(date.getFullYear(),date.getMonth(),date.getDate())-easter)/86400000);return difference===-2||difference===-1}
function addBusinessDays(start,days){const date=new Date(start.getFullYear(),start.getMonth(),start.getDate());let remaining=days;while(remaining>0){date.setDate(date.getDate()+1);const weekday=date.getDay();if(weekday!==0&&weekday!==6&&!isChileHoliday(date))remaining--}return date}
const estimatedDate=()=>addBusinessDays(new Date(),state.fulfillment==='delivery'?7:5);
const estimatedDateLabel=()=>new Intl.DateTimeFormat('es-CL',{weekday:'long',day:'numeric',month:'long'}).format(estimatedDate());
// Safari/iOS puede presentar ciertos símbolos Unicode como emoji. Usamos
// equivalentes ASCII para los iconos decorativos y de acción.
function normalizeTextSymbols(root=document){
 const replacements={'↗':'>','↙':'<','↔':'<>','→':'>','←':'<','↑':'^','↓':'v','✳':'*','✷':'*','✧':'*','✕':'x','×':'x','＋':'+','⤵':'v'};
 const pattern=/↗|↙|↔|→|←|↑|↓|✳|✷|✧|✕|×|＋|⤵/g;
 const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);
 const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);
 nodes.forEach(node=>{node.nodeValue=node.nodeValue.replace(pattern,symbol=>replacements[symbol])});
}
document.querySelector('#app').innerHTML=`
<div class="announcement"><span class="announcement-message">De tu cabeza a tu polera. Así de simple.<svg class="announcement-mark" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2 14.3 9.7 22 12l-7.7 2.3L12 22l-2.3-7.7L2 12l7.7-2.3L12 2Z"/></svg></span><span class="announcement-origin">Hecho a tu pinta, en <img class="chile-flag" src="/chile-flag.png" alt=""> Chile.</span></div>
<header><a class="logo" href="#" aria-label="Polerama inicio">polerama<span>✳</span></a><nav><a href="#como">Cómo funciona</a><a href="#caminos">El estudio</a><a href="#poleras">Nuestras poleras</a></nav><button class="nav-cta" data-start="ready">Crear mi polera ↗</button></header>
<main><section class="hero"><div class="hero-copy"><span class="eyebrow"><i></i> PARA IDEAS QUE NO CABEN EN UN CATÁLOGO</span><h1>Tu idea<br>favorita,<br><span>puesta.</span><svg class="hero-star" viewBox="0 0 100 100" aria-hidden="true"><path d="M50 0l9 33 27-20-19 28 33 9-33 9 19 28-27-20-9 33-9-33-28 20 20-28L0 50l33-9-20-28 28 20Z" fill="#dfff6b" stroke="#242720" stroke-width="2"/></svg></h1><p>Tu mascota, ese recuerdo, una idea muy tuya.<br>Lo convertimos en la polera que solo tú tienes.</p><button class="button dark" data-start="ready">Dale forma a tu idea <span>↗</span></button><div class="hero-note"><span class="mini-faces">☺ ☻ ☺</span><span>Diseñada por ti. Creada contigo.</span></div></div>
<div class="hero-art"><div class="art-grid"></div><span class="art-label">EL LIENZO ERES TÚ</span><div class="bubble">Esta puede ser tu mascota <span aria-hidden="true"><svg viewBox="0 0 70 90" role="img"><path d="M8 8 C50 12, 65 32, 57 55 C52 69, 43 76, 31 78" fill="none" stroke="currentColor" stroke-width="4" stroke-linecap="round"/><path d="M19 64 L30 79 L43 66" fill="none" stroke="currentColor" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/></svg></span></div><div id="hero-viewer"><div class="shirt hero-shirt"><div class="shirt-neck"></div></div></div><button class="hero-personalize" data-start="ready">＋ Agrega tu diseño</button><div class="hero-swatches"><button data-hero-color="#ffffff" style="--swatch:#ffffff" aria-label="Polera blanca" class="chosen"></button><button data-hero-color="#202124" style="--swatch:#202124" aria-label="Polera negra"></button><button data-hero-color="#e8e0cf" style="--swatch:#e8e0cf" aria-label="Polera blanco vintage"></button><button data-hero-color="#8daec3" style="--swatch:#8daec3" aria-label="Polera azul zen"></button></div><div class="floating-chip pink">ÚNICA.<br>COMO TÚ. <span>✷</span></div><div class="floating-chip cream"><span>✧</span> Cero poleras aburridas.</div><div class="art-bottom"><span>ARRASTRA PARA GIRAR · 360°</span><span>↙ HECHA A TU PINTA</span></div></div></section>
<div class="ticker"><span>TU FOTO</span> ✳ <span>TU IDEA</span> ✳ <span>TU DISEÑO DE IA</span> ✳ <span>TU POLERA</span> ✳ <span>TU FOTO</span> ✳ <span>TU IDEA</span> ✳ <span>TU DISEÑO DE IA</span> ✳</div>
<section id="caminos" class="section"><div class="section-heading"><div><span class="eyebrow">PRIMER PASO · ELIGE TU CAMINO</span><h2>¿Qué tienes en mente?</h2></div><p>Tres caminos para llegar<br>a tu polera favorita.</p></div><div class="paths"><button class="path lilac" data-start="ready"><span class="path-top">01 / TENGO DISEÑO <span>↗</span></span><div class="path-art upload-art"><div>↑<small>SUBE TU DISEÑO</small></div><svg class="brand-mark mark-lilac" viewBox="0 0 100 100" aria-hidden="true"><path d="M50 0 60 33 88 12 70 42 100 50 69 58 86 88 57 67 49 100 40 66 12 86 30 57 0 49 33 40 15 12 43 33Z"/></svg></div><h3>Lo veo en 3D.</h3><p>Sube tu archivo. Si cumple el control técnico, lo visualizas sobre la polera.</p><span class="text-link">Tengo diseño <span>↗</span></span></button><button class="path lime" data-start="improve"><span class="path-top">02 / TE LO REVISO <span>↗</span></span><div class="path-art improve-art"><span>✳</span><b>✳</b><small>PREVIO ABONO</small></div><h3>Te lo reviso.</h3><p>Si necesita trabajo para imprimir, lo revisamos previo abono. Ese pago se descuenta de tu polera.</p><span class="text-link">Te lo reviso ↗</span></button><button class="path pink" data-start="custom"><span class="path-top">03 / MI IDEA <span>↗</span></span><div class="path-art custom-art"><span>¿y si…?</span><svg class="brand-mark mark-four" viewBox="0 0 100 100" aria-hidden="true"><path d="M50 4 61 39 96 50 61 61 50 96 39 61 4 50 39 39Z"/></svg></div><h3>Mi idea, desde cero.</h3><p>Cuéntanos qué imaginas. Creamos una propuesta contigo, con cuota previa acreditable.</p><span class="text-link">Mi idea <span>↗</span></span></button></div></section>
<section class="how section" id="como"><div><span class="eyebrow">DEL “¿Y SI…?” AL “¡ES MÍA!”</span><h2>Así nace tu<br>próxima favorita.</h2><p>Un proceso simple.<br>Un resultado muy tuyo.</p><a class="text-link" href="#caminos">Vamos a crear ↗</a></div><ol><li><span>01</span><div><h3>Tú pones la idea.</h3><p>Sube tu archivo o cuéntanos qué imaginas. Elige tu polera, talla y color.</p></div></li><li><span>02</span><div><h3>La hacemos realidad.</h3><p>Si tu archivo necesita mejoras, pagas una cuota de revisión que se descuenta de tu polera. Los diseños desde cero se cotizan.</p></div></li><li><span>03</span><div><h3>La ves. Te enamoras. La apruebas.</h3><p>“Tengo diseño” permite ver en 3D los archivos que cumplen el control técnico. En trabajos creativos revisas la propuesta del taller antes de aprobar.</p></div></li><li><span>04</span><div><h3>De nuestra mesa a tu clóset.</h3><p>Con tu aprobación y pago completo, pasa a impresión. Coordinamos la entrega contigo.</p></div></li></ol></section>
<section class="section garments" id="poleras"><div class="section-heading"><div><span class="eyebrow">ELIGE TU LIENZO</span><h2>Una idea. Tu forma de usarla.</h2></div><p>El diseño lo pones tú.<br>La polera, nosotros.</p></div><div class="garment-grid">${Object.entries(products).map(([id,p],i)=>`<button class="garment" data-kind="${id}"><div class="garment-visual g${i}"><span class="garment-tag">${['EL CLÁSICO DE SIEMPRE','MÁS ESPACIO, MÁS ACTITUD','PEQUEÑOS, PERO ÚNICOS'][i]}</span><div class="shirt blank ${id}"><div class="shirt-neck"></div><span>${['YOUR<br>IDEA<br>HERE.','MAKE<br>ROOM.','mini<br>idea ☺'][i]}</span></div><span class="round-arrow">↗</span></div><div class="garment-meta"><h3>${p.name}</h3><span>${money(p.price)}</span></div><p>${['Tu favorita para todos los días.','Calce amplio, estilo sin esfuerzo.','Grandes ideas en tallas pequeñas.'][i]}</p></button>`).join('')}</div><p class="price-note">Valores base de polera. Mejoras y diseños a medida se cotizan antes de pedir el abono.</p></section>
<section class="closing"><svg class="brand-mark mark-asterisk" viewBox="0 0 100 100" aria-hidden="true"><path d="M50 5v90M5 50h90M18 18l64 64M82 18 18 82"/></svg><h2>Si lo imaginas,<br>te queda bien.</h2><button class="button dark" data-start="custom">Hagamos esa polera ↗</button><p>Sin catálogo. Sin límites a tu idea. Con mucha personalidad.</p></section>
<section class="faq section"><div class="faq-intro"><span class="eyebrow">ANTES DE EMPEZAR</span><h2>Antes de darle al botón.</h2><p>Todo lo necesario para pasar de tu idea a una polera lista para usar.</p><div class="faq-facts"><span>Archivos hasta 50 MB</span><span>Frente o espalda</span><span>Despachos en Chile</span></div><a class="faq-contact" href="https://wa.me/56965217926" target="_blank" rel="noopener">¿Te quedó una duda?<strong>Hablemos por WhatsApp →</strong></a></div><div class="faq-list">${[['¿Puedo subir un diseño hecho con IA?','Sí. En “Tengo diseño” comprobamos formato, tamaño y resolución para un estampado de hasta 28 × 40 cm, en frente o espalda. Si la resolución no alcanza, activamos “Te lo reviso”.'],['¿Cuándo pago la cuota?','“Te lo reviso” y “Mi idea” requieren una cuota previa. Esa cuota se descuenta del precio final de tu polera y no se cobra dos veces.'],['¿Y si todavía no tengo un diseño?','Elige “Mi idea”, cuéntanos qué imaginas y adjunta una referencia si quieres. El taller prepara una propuesta contigo.'],['¿Puedo revisar mi polera antes de imprimir?','La previsualización 3D está disponible solo en “Tengo diseño”, si el archivo cumple el control técnico. En “Te lo reviso” y “Mi idea” revisas la propuesta que prepara el taller. El estampado ocupa una sola cara: frente o espalda.']].map(([q,a])=>`<details><summary>${q}<span>+</span></summary><p>${a}</p></details>`).join('')}</div></section></main>
<footer><a class="logo" href="#">polerama<span>✳</span></a><p>Ideas que se llevan puestas.</p><span>Hecho con personalidad en Chile. © ${new Date().getFullYear()}</span><a href="#como">Cómo funciona ↗</a></footer><div class="demo-banner">Vista de prueba · Las cuentas, solicitudes y pagos aún no están conectados.</div>
<dialog id="studio"><div class="dialog-header"><a class="logo" href="#">polerama<span>✳</span></a><span>TU ESTUDIO CREATIVO</span><button class="icon-btn close-button" data-close aria-label="Cerrar estudio"><span aria-hidden="true"></span></button></div><div class="studio-body"><div class="preview"><div id="reference-panel"></div><div id="live-preview" hidden><span class="eyebrow">UNA VISTA A TU PRÓXIMA FAVORITA</span><div id="viewer"><div class="shirt preview-fallback"><div class="shirt-neck"></div><img alt="Tu diseño sobre la polera" hidden/></div></div><span class="viewer-note">Arrastra para girar · Vista 3D referencial</span><button id="reset-view" class="small-button">Ver lado elegido</button></div></div><div class="studio-controls"><div class="steps" aria-label="Progreso del diseño"></div><form id="design-form"><div id="step-content"></div><div class="form-navigation"><button type="button" id="back" class="small-button">Volver</button><button type="submit" class="button dark" id="next">Siguiente</button></div></form></div></div></dialog>
<dialog id="size-guide-modal" aria-labelledby="size-guide-title"><div class="size-guide-header"><div><span class="eyebrow">GUÍA DE TALLAS</span><h2 id="size-guide-title">Encuentra tu medida.</h2></div><button type="button" class="icon-btn close-button" data-size-close aria-label="Cerrar guía de tallas"><span aria-hidden="true"></span></button></div><div class="size-guide-body"><div class="measure-visual"><svg viewBox="0 0 420 390" role="img" aria-labelledby="measure-title measure-desc"><title id="measure-title">Medición del ancho de una polera</title><desc id="measure-desc">La polera se mide en línea recta desde una axila hasta la otra.</desc><path class="measure-shirt" d="M133 55 174 34c9 21 63 21 72 0l41 21 75 60-45 63-34-24v195H137V154l-34 24-45-63 75-60Z"/><path class="measure-neck" d="M174 34c5 35 67 35 72 0"/><path class="measure-line" d="M137 158H283"/><path class="measure-arrow" d="m137 158 16-11m-16 11 16 11m130-11-16-11m16 11-16 11"/><circle cx="137" cy="158" r="6"/><circle cx="283" cy="158" r="6"/><text x="210" y="138" text-anchor="middle">AXILA A AXILA</text><text class="measure-a" x="210" y="190" text-anchor="middle">A</text></svg><div class="measure-caption"><strong>Medida A · Ancho</strong><span>Siempre en línea recta, sin estirar la tela.</span></div></div><div class="measure-info"><ol class="measure-steps"><li><b>1</b><span>Busca una polera que te quede como te gusta.</span></li><li><b>2</b><span>Extiéndela plana sobre una mesa.</span></li><li><b>3</b><span>Mide de axila a axila y compara el resultado.</span></li></ol><div class="visual-size-table"><div class="size-table-head"><span>Talla</span><span>Ancho A</span></div>${[['XS','44 cm'],['S','48 cm'],['M','52 cm'],['L','56 cm'],['XL','60 cm'],['XXL','64 cm']].map(([size,width])=>`<button type="button" data-guide-size="${size}"><strong>${size}</strong><span>${width}</span></button>`).join('')}</div><p class="measure-note">Las medidas son aproximadas y pueden variar hasta 1–2 cm. Si quedas entre dos tallas, elige la mayor para un calce más suelto.</p></div></div></dialog>
<dialog id="space"><div class="dialog-header"><h2>Tu espacio creativo</h2><button data-close class="icon-btn close-button" aria-label="Cerrar"><span aria-hidden="true"></span></button></div><div class="space-content"><span class="eyebrow">TUS IDEAS VIVEN AQUÍ</span><p>Cuando activemos las cuentas podrás seguir tus solicitudes, revisar propuestas y aprobar tu diseño desde este espacio.</p><div class="notice">Esta versión es una demostración. Todavía no crea cuentas ni envía solicitudes.</div><div id="saved-request"></div><button class="button dark" id="space-create">Probar el estudio ↗</button></div></dialog><div id="toast" role="status"></div>`;

document.title='droska — SHIRT';document.querySelectorAll('.logo').forEach(el=>{el.innerHTML='droska<span>SHIRT</span>';el.setAttribute('aria-label','droska SHIRT inicio')});const favicon=document.querySelector('link[rel="icon"]');if(favicon)favicon.href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='18' fill='%23f955a5'/%3E%3Ctext x='10' y='47' font-size='42' font-family='Arial' font-weight='bold'%3Ed%3C/text%3E%3C/svg%3E";
// Cuenta y carro de demostración: se guardan solo en este navegador hasta conectar el backend.
const CART_KEY='droska-cart-demo';
const supabase=createClient('https://dgndcklmmnnxyqfmnckh.supabase.co','sb_publishable_J2zSgCPaW1rENVCdEuYGNQ_62EhSxtS');
const readLocal=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
let account=null,cart=readLocal(CART_KEY,[]);
const saveLocal=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value))}catch{}};
const header=document.querySelector('header');
const accountButton=document.createElement('button');accountButton.type='button';accountButton.className='account-trigger';accountButton.setAttribute('aria-label','Abrir acceso de cuenta');
const cartButton=document.createElement('button');cartButton.type='button';cartButton.className='cart-trigger';cartButton.setAttribute('aria-label','Abrir carro de compras');
header?.insertBefore(accountButton,header.querySelector('.nav-cta'));header?.insertBefore(cartButton,header.querySelector('.nav-cta'));
document.body.insertAdjacentHTML('beforeend',`<dialog id="account-modal" class="commerce-modal"><div class="commerce-head"><div><span class="eyebrow">TU ESPACIO</span><h2 id="account-title">Bienvenida a droska.</h2></div><button type="button" class="commerce-close" data-commerce-close aria-label="Cerrar">×</button></div><div id="account-content"></div></dialog><dialog id="cart-modal" class="commerce-modal"><div class="commerce-head"><div><span class="eyebrow">TU PEDIDO</span><h2>Carro de compras</h2></div><button type="button" class="commerce-close" data-commerce-close aria-label="Cerrar">×</button></div><div id="cart-content"></div></dialog>`);
const accountModal=document.querySelector('#account-modal'),cartModal=document.querySelector('#cart-modal');
const safe=value=>String(value||'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function updateCommerceNav(){const itemCount=cart.reduce((sum,item)=>sum+item.quantity,0);accountButton.innerHTML=account?`<span class="account-initial">${safe(account.name).slice(0,1).toUpperCase()}</span><span>Hola, ${safe(account.name.split(' ')[0])}</span>`:'<span class="account-icon" aria-hidden="true">◯</span><span>Ingresar</span>';cartButton.innerHTML=`<span aria-hidden="true">Bag</span><b>${itemCount}</b>`;cartButton.classList.toggle('has-items',itemCount>0)}
function accountFromUser(user){return user?{id:user.id,name:user.user_metadata?.full_name||user.email?.split('@')[0]||'Creativa',email:user.email||''}:null}
function renderAccount(mode='login'){
 if(account){document.querySelector('#account-title').textContent=`Hola, ${account.name.split(' ')[0]}.`;document.querySelector('#account-content').innerHTML=`<div class="account-welcome"><span class="account-initial large">${safe(account.name).slice(0,1).toUpperCase()}</span><div><strong>${safe(account.name)}</strong><small>${safe(account.email)}</small></div></div><p class="commerce-copy">Tu información está protegida por Supabase y quedará lista para coordinar tus próximas poleras.</p><button type="button" class="button dark commerce-wide" id="logout-account">Cerrar sesión</button>`;document.querySelector('#logout-account').onclick=async()=>{const {error}=await supabase.auth.signOut();if(error)return toast(error.message);account=null;updateCommerceNav();renderAccount();toast('Sesión cerrada.');return};return}
 const isRegister=mode==='register';document.querySelector('#account-title').textContent=isRegister?'Crea tu cuenta.':'Qué bueno verte.';document.querySelector('#account-content').innerHTML=`<p class="commerce-copy">${isRegister?'Guarda tus datos y sigue tus pedidos desde un solo lugar.':'Ingresa para recuperar tus datos y avanzar más rápido.'}</p><form id="account-form" class="account-form">${isRegister?'<label>Nombre completo<input name="name" required autocomplete="name" placeholder="Cómo te llamas"></label>':''}<label>Email<input name="email" required type="email" autocomplete="email" placeholder="tu@email.com"></label><label>Contraseña<input name="password" required type="password" minlength="6" autocomplete="${isRegister?'new-password':'current-password'}" placeholder="Mínimo 6 caracteres"></label><button class="button dark commerce-wide" type="submit">${isRegister?'Crear mi cuenta':'Ingresar'}</button></form><button type="button" class="commerce-switch" id="account-switch">${isRegister?'Ya tengo cuenta · Ingresar':'¿Primera vez por aquí? · Crear cuenta'}</button><small class="commerce-note">Demo local: no enviamos ni almacenamos contraseñas en un servidor.</small>`;
 document.querySelector('#account-switch').onclick=()=>renderAccount(isRegister?'login':'register');
 document.querySelector('#account-form').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,data=new FormData(form),email=String(data.get('email')).trim(),password=String(data.get('password')),name=isRegister?String(data.get('name')).trim():'';const submit=form.querySelector('[type="submit"]');submit.disabled=true;submit.textContent='Un momento…';const result=isRegister?await supabase.auth.signUp({email,password,options:{data:{full_name:name},emailRedirectTo:window.location.origin}}):await supabase.auth.signInWithPassword({email,password});submit.disabled=false;submit.textContent=isRegister?'Crear mi cuenta':'Ingresar';if(result.error)return toast(result.error.message);state.email=state.email||email;if(isRegister&&name)state.firstName=state.firstName||name.split(' ')[0];if(!result.data.session){accountModal.close();toast('Revisa tu correo para confirmar la cuenta antes de ingresar.');return}account=accountFromUser(result.data.user);updateCommerceNav();accountModal.close();toast(`Listo, ${account.name.split(' ')[0]}. Tu sesión está activa.`)};
}
function cartTotal(){return cart.reduce((sum,item)=>sum+item.price*item.quantity,0)}
function renderCart(){const target=document.querySelector('#cart-content');if(!cart.length){target.innerHTML='<div class="cart-empty"><span>✳</span><h3>Aún no hay poleras aquí.</h3><p>Termina de personalizar una y agrégala cuando estés lista.</p><button type="button" class="button dark commerce-wide" id="cart-start">Crear mi polera</button></div>';document.querySelector('#cart-start').onclick=()=>{cartModal.close();openStudio('ready')};return}target.innerHTML=`<div class="cart-list">${cart.map(item=>`<article class="cart-item"><div class="cart-art" style="--cart-color:${safe(item.color)}"><span>${safe(item.initial)}</span></div><div class="cart-item-copy"><strong>Polera ${safe(item.kind)}</strong><small>Talla ${safe(item.size)} · ${safe(item.sides)}</small><button type="button" data-cart-remove="${safe(item.id)}">Quitar</button></div><div class="cart-price"><strong>${money(item.price*item.quantity)}</strong><div class="quantity"><button type="button" data-cart-quantity="${safe(item.id)}" data-change="-1" aria-label="Reducir cantidad">−</button><span>${item.quantity}</span><button type="button" data-cart-quantity="${safe(item.id)}" data-change="1" aria-label="Aumentar cantidad">+</button></div></div></article>`).join('')}</div><div class="cart-total"><span>Subtotal</span><strong>${money(cartTotal())}</strong><small>El despacho se calcula en el checkout.</small></div><button type="button" class="button dark commerce-wide" id="cart-checkout">Ir a pagar <span>→</span></button>`;target.querySelectorAll('[data-cart-remove]').forEach(button=>button.onclick=()=>{cart=cart.filter(item=>item.id!==button.dataset.cartRemove);saveLocal(CART_KEY,cart);updateCommerceNav();renderCart()});target.querySelectorAll('[data-cart-quantity]').forEach(button=>button.onclick=()=>{const item=cart.find(entry=>entry.id===button.dataset.cartQuantity);if(!item)return;item.quantity+=Number(button.dataset.change);if(item.quantity<1)cart=cart.filter(entry=>entry!==item);saveLocal(CART_KEY,cart);updateCommerceNav();renderCart()});document.querySelector('#cart-checkout').onclick=()=>{cartModal.close();if(!account){renderAccount('register');accountModal.showModal();toast('Crea tu cuenta para continuar con el pago.');return}openStudio('ready')};}
function addCurrentToCart(){const product=products[state.kind],pricing=orderTotal(product.price,printChoice(),state.qualityReview?QUALITY_ADJUSTMENT_CLP:0);cart.push({id:`shirt-${Date.now()}`,kind:product.name,size:state.size,sides:printSidesLabel(),color:state.color,initial:state.files[state.printSide]?.slice(0,1).toUpperCase()||'✳',price:pricing.total,quantity:1});saveLocal(CART_KEY,cart);updateCommerceNav();toast('Tu polera quedó guardada en el carro.');}
accountButton.onclick=()=>{renderAccount();accountModal.showModal()};cartButton.onclick=()=>{renderCart();cartModal.showModal()};document.querySelectorAll('[data-commerce-close]').forEach(button=>button.onclick=()=>button.closest('dialog').close());updateCommerceNav();supabase.auth.getUser().then(({data})=>{account=accountFromUser(data.user);updateCommerceNav()});supabase.auth.onAuthStateChange((_event,session)=>{account=accountFromUser(session?.user);updateCommerceNav()});
document.querySelectorAll('.garment-meta > span').forEach(el=>el.textContent='Elige en el estudio');
document.querySelector('.price-note')?.remove();
document.querySelector('.how')?.remove();document.querySelector('footer>a:last-child')?.setAttribute('href','#caminos');
const extraFaqs=[
 ['¿Qué formatos puedo enviar?','Aceptamos JPG, PNG y WEBP de hasta 50 MB. Si el archivo no cumple la resolución mínima, te avisaremos antes de avanzar.'],
 ['¿Cuánto demora mi pedido?','El plazo depende de la revisión, aprobación y producción. Te confirmaremos una fecha estimada antes de pedir el abono.'],
 ['¿Puedo pedir cambios al diseño?','Sí. En “Te lo reviso” y “Mi idea” coordinamos los ajustes contigo antes de aprobar la propuesta final.'],
 ['¿Hacen despachos a regiones?','Coordinamos la entrega dentro de Chile. El costo y plazo de despacho se informan junto con la cotización.'],
 ['¿Qué medios de pago aceptan?','El abono y el saldo se habilitarán con un medio de pago seguro cuando activemos el checkout. Esta demo no realiza cobros.'],
 ['¿Puedo estampar frente y espalda?','Sí. Selecciona “Ambos” al cargar tu diseño; el recargo se confirma antes del pago.']
];
const faqList=document.querySelector('.faq-list');extraFaqs.forEach(([question,answer])=>{if(!faqList)return;const item=document.createElement('details');const summary=document.createElement('summary');summary.textContent=question;const toggle=document.createElement('span');toggle.textContent='+';summary.append(toggle);const copy=document.createElement('p');copy.textContent=answer;item.append(summary,copy);faqList.append(item)});faqList?.querySelectorAll('details').forEach(item=>item.addEventListener('toggle',()=>{if(!item.open)return;faqList.querySelectorAll('details[open]').forEach(other=>{if(other!==item)other.open=false})}));
const ticker=document.querySelector('.ticker');if(ticker){const items=[...ticker.childNodes].map(node=>node.cloneNode(true));const track=document.createElement('div');track.className='ticker-track';track.append(...items,...items.map(node=>node.cloneNode(true)));ticker.replaceChildren(track)}
const garmentColors={basic:'#f4f0e5',over:'#202124',kids:'#202124'};
const garmentSamples={basic:'/laika.png',over:'/claire.png',kids:'/metal-gear.png'};
const garmentPrintScale={basic:1.1,over:1.15,kids:.92};
const garmentViews={basic:{angle:-.12,distance:4.62},over:{angle:.32,distance:4.5},kids:{angle:-.26,distance:4.72}};
const garmentViewers=new Map();
const garmentImage=kind=>state.images.front||state.images.back||garmentSamples[kind];
const garmentColor=kind=>(state.images.front||state.images.back)&&state.artworkTone==='light'?'#202124':garmentColors[kind];
function syncGarmentSamples(){
 garmentViewers.forEach((garmentViewer,kind)=>garmentViewer.update({...state,kind,color:garmentColor(kind),image:garmentImage(kind),printScale:garmentPrintScale[kind],printSide:'front',assessment:null}));
}
document.querySelectorAll('.garment-visual').forEach(visual=>{
 const kind=visual.closest('.garment')?.dataset.kind;if(!kind)return;
 const viewport=document.createElement('div');viewport.className='garment-viewer';viewport.setAttribute('aria-hidden','true');visual.append(viewport);
 import('./garment.js').then(module=>module.createViewer(viewport,{kind,color:garmentColor(kind),image:garmentImage(kind),printScale:garmentPrintScale[kind],printSide:'front'},{viewAngle:garmentViews[kind].angle,cameraDistance:garmentViews[kind].distance})).then(garmentViewer=>{garmentViewers.set(kind,garmentViewer);syncGarmentSamples()}).catch(()=>{viewport.remove();visual.querySelector('.blank')?.classList.add('viewer-fallback')});
});
const designPath=document.querySelector('.path[data-start="ready"]');if(designPath){const title=designPath.querySelector('h3');const copy=designPath.querySelector('p');if(title)title.innerHTML='Sube, mira,<br>decide.';if(copy)copy.textContent='Comprueba cómo se ve tu diseño sobre la polera antes de elegir.';const flow=document.createElement('div');flow.className='design-flow';flow.innerHTML='<span><b>01</b> Sube</span><i>→</i><span><b>02</b> Mira en 3D</span><i>→</i><span><b>03</b> Elige</span>';copy?.after(flow);const link=designPath.querySelector('.text-link');if(link)link.innerHTML='Subir mi diseño <span>↗</span>';designPath.remove()}
const whatsappFloat=document.createElement('a');whatsappFloat.className='whatsapp-float';whatsappFloat.href='https://wa.me/56965217926';whatsappFloat.target='_blank';whatsappFloat.rel='noreferrer';whatsappFloat.setAttribute('aria-label','Abrir chat de ayuda');whatsappFloat.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20 11.5a7.5 7.5 0 0 1-8 7.5 8.8 8.8 0 0 1-3.7-.8L4 20l1.5-3.7A7.2 7.2 0 0 1 4 12a7.5 7.5 0 0 1 8-7.5 7.5 7.5 0 0 1 8 7Z"/><circle cx="8.5" cy="12" r=".8"/><circle cx="12" cy="12" r=".8"/><circle cx="15.5" cy="12" r=".8"/></svg><span>¿Dudas?</span>';document.body.append(whatsappFloat);
const whatsappFooter=document.createElement('a');whatsappFooter.className='whatsapp-link';whatsappFooter.href='https://wa.me/56965217926';whatsappFooter.target='_blank';whatsappFooter.rel='noreferrer';whatsappFooter.textContent='¿Dudas? Escríbeme por WhatsApp ↗';document.querySelector('footer')?.insertBefore(whatsappFooter,document.querySelector('footer>span'));
const spaceContent=document.querySelector('#space .space-content');if(spaceContent){const avatar=document.createElement('div');avatar.className='space-avatar';avatar.innerHTML='<img src="/cris.png" alt="Avatar de Cristian"><div><span class="eyebrow">TU ESTUDIO TOLSKA</span><strong>Cristian</strong></div>';spaceContent.prepend(avatar)}
const humanStory=document.createElement('section');humanStory.className='human-story section';humanStory.innerHTML='<div class="human-story-avatar"><div class="human-story-avatar-circle"><img class="avatar-body-layer" src="/cris.png" alt="Cristian, fundador de droska SHIRT"></div><img class="avatar-head-layer" src="/cris.png" alt="" aria-hidden="true"></div><div><span class="eyebrow">DETRÁS DE CADA POLERA</span><h2>Hola, soy Cristian.</h2><p class="human-story-lead">No es una fábrica. Es una mesa en mi casa.</p><p>Empecé droska SHIRT para estar más cerca de Benja, mi hijo. Cada pedido se trabaja uno a uno, con tiempo y cariño. Gracias por ayudarnos a seguir eligiendo estar juntos.</p></div>';document.querySelector('.closing')?.before(humanStory);
const storyParagraphs=[...humanStory.querySelectorAll('p')];if(storyParagraphs.length>1){const unified=storyParagraphs.map(p=>p.textContent.trim()).join(' ');storyParagraphs[0].textContent=unified;storyParagraphs.slice(1).forEach(p=>p.remove())}
const closingSection=document.querySelector('.closing');if(closingSection){const storyGroup=document.createElement('section');storyGroup.className='human-closing';humanStory.before(storyGroup);storyGroup.append(humanStory,closingSection)}
const heroMessage=document.querySelector('.hero-copy>p');if(heroMessage)heroMessage.innerHTML='Tu mascota, ese recuerdo, una idea muy tuya.<br>Lo convertimos en la polera que solo tú tienes.<br><strong>También puedes enviarnos tu diseño generado con IA.</strong>';
const heroEyebrow=document.querySelector('.hero-copy>.eyebrow');if(heroEyebrow)heroEyebrow.innerHTML='<i></i> DEL PROMPT A TU POLERA';const heroTitle=document.querySelector('.hero-copy h1');if(heroTitle){heroTitle.classList.add('hero-gpt');heroTitle.setAttribute('aria-label','Trae tu diseño de GPT, foto, dibujo o idea a una polera.');heroTitle.innerHTML='Trae tu<br><span class="hero-variable-wrap"><span id="hero-variable-word" aria-hidden="true">diseño de GPT</span></span><br><span class="hero-tail">a una <em>polera.</em></span><svg class="hero-star" viewBox="0 0 100 100" aria-hidden="true"><path d="M50 0 59 34 86 14 69 41 100 50 69 59 86 86 59 66 50 100 41 66 14 86 31 59 0 50 31 41 14 14 41 34Z" fill="#dfff6b" stroke="#242720" stroke-width="3" stroke-linejoin="round"/></svg>';const words=['diseño de GPT','foto','dibujo','idea'];const word=heroTitle.querySelector('#hero-variable-word');let wordIndex=0;const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;window.setInterval(()=>{wordIndex=(wordIndex+1)%words.length;if(reducedMotion){word.textContent=words[wordIndex];return}word.classList.add('is-leaving');window.setTimeout(()=>{word.textContent=words[wordIndex];word.classList.remove('is-leaving');word.classList.add('is-entering');window.setTimeout(()=>word.classList.remove('is-entering'),420)},190)},2700)}if(heroMessage)heroMessage.innerHTML='Acá lo ajustamos para que se vea bien, se imprima mejor<br>y quede realmente a tu pinta.';const heroCta=document.querySelector('.hero-copy [data-start="ready"]');if(heroCta)heroCta.innerHTML='Traer mi diseño <span>↗</span>';
const studio=document.querySelector('#studio');let viewer,heroViewer,viewerPromise;const uploadVersions={front:0,back:0};
document.querySelector('#viewer').addEventListener('preview-error',()=>toast('No pudimos mostrar ese estampado. Prueba reemplazando el archivo.'));
const colorDock=document.createElement('div');colorDock.className='color-dock';colorDock.innerHTML='<span>COLOR</span>'+[['#ffffff','Blanco'],['#202124','Negro'],['#e8e0cf','Blanco vintage'],['#8daec3','Azul zen']].map(([c,n])=>`<button type="button" aria-label="${n}" title="${n}" data-color="${c}" style="--swatch:${c}"></button>`).join('');document.querySelector('.preview').append(colorDock);
const sizeDock=document.createElement('div');sizeDock.className='size-dock';sizeDock.innerHTML='<span>TAMAÑO</span><input id="print-scale" type="range" min="0.55" max="1.35" step="0.01" value="1" aria-label="Tamaño del estampado" title="Arrastra para cambiar el tamaño"><output id="print-scale-value">100%</output>';document.querySelector('.preview').append(sizeDock);
const maxPrintScale=()=>{const a=state.assessment;if(!a?.printWidth||!a?.printHeight)return state.isDefault?1:1.35;return Math.max(.55,Math.min(1.35,28/a.printWidth,40/a.printHeight))};
const syncScaleControl=()=>{const input=sizeDock.querySelector('input');const max=maxPrintScale();input.max=max.toFixed(2);state.printScale=Math.min(state.printScale,max);input.value=state.printScale;sizeDock.querySelector('output').textContent=Math.round(state.printScale*100)+'%';input.title=`Máximo ${Math.round(max*100)}% · estampado hasta 28 × 40 cm`};
sizeDock.querySelector('input').oninput=e=>{state.printScale=Math.min(Number(e.target.value),maxPrintScale());syncScaleControl();viewer?.update(previewState())};
document.querySelector('.path[data-start="improve"]')?.remove();
const pathsIntro=document.querySelector('#caminos .section-heading p');if(pathsIntro)pathsIntro.innerHTML='Un camino para llegar<br>a tu polera favorita.';const ideaPath=document.querySelector('.path[data-start="custom"] .path-top');if(ideaPath&&ideaPath.firstChild)ideaPath.firstChild.textContent='01 / MI IDEA ';
const ideaCard=document.querySelector('.path[data-start="custom"]');if(ideaCard){const ideaCopy=ideaCard.querySelector('p');if(ideaCopy)ideaCopy.outerHTML='<div class="path-stepper"><div><b>01</b><i class="step-icon"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m14 4 6 6M4 20l3-7L17 3l4 4L11 17l-7 3Zm2-6 4 4M5 5h3M6.5 3.5v3M18 14h3M19.5 12.5v3"/></svg></i><span>Haz tu diseño con IA.<small>O con lo que quieras: foto, dibujo, etc.</small></span></div><div><b>02</b><i class="step-icon"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4"/></svg></i><span>Descárgalo y envíanoslo.</span></div><div><b>03</b><i class="step-icon"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21 11a8 8 0 0 1-9 8 9 9 0 0 1-4-.9L3 20l1.8-4A8 8 0 1 1 21 11Z"/></svg></i><span>Aquí lo mejoramos contigo.</span></div></div>';ideaCard.querySelector('.path-art')?.insertAdjacentHTML('beforeend','<img class="custom-doodles" src="/idea-collage.png" alt=""><img class="custom-shirt-image" src="/idea-shirt.png" alt="Ejemplo de polera personalizada">')}
const ideaLink=document.querySelector('.path[data-start="custom"] .text-link');if(ideaLink)ideaLink.innerHTML='Empezar mi idea <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14m-6-6 6 6-6 6"/></svg>';
const primaryCtaMarkup='Empezar mi idea <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14m-6-6 6 6-6 6"/></svg>';
const primaryCtas=[...document.querySelectorAll('.nav-cta[data-start],.hero-copy [data-start],.hero-personalize[data-start],.closing [data-start]')];
primaryCtas.forEach(cta=>{cta.classList.add('primary-idea-cta');cta.dataset.start='ready';cta.innerHTML=primaryCtaMarkup});
ideaLink?.classList.add('primary-idea-cta');
function previewState(){const isSample=!state.images?.[state.printSide]&&state.isDefault;const sideImage=state.images?.[state.printSide]||(isSample?'/laika.png':'');const sideAssessment=state.assessments?.[state.printSide]||state.assessment;return {...state,image:state.mode==='ready'&&sideImage&&(isSample||sideAssessment?.qualifies||state.qualityAccepted)?sideImage:'',assessment:sideAssessment}}
import('./garment.js').then(async m=>{heroViewer=await m.createViewer(document.querySelector('#hero-viewer'),previewState(),{hero:true})}).catch(()=>{document.querySelector('.art-bottom span').textContent='TU POLERA EN BLANCO · LISTA PARA CREAR'});
function syncPreview(){
 const sideImage=state.images?.[state.printSide]||'';
 const isForging=state.step<4,showMockup=state.step>=4&&Boolean(sideImage),renderState=isForging?{...state,image:'',assessment:null,isDefault:false}:previewState();
 const livePreview=document.querySelector('#live-preview');livePreview.hidden=!(isForging||showMockup);livePreview.classList.toggle('is-forging',isForging);
 const liveEyebrow=livePreview.querySelector(':scope > .eyebrow');if(liveEyebrow)liveEyebrow.hidden=false;
 const viewerNote=document.querySelector('.viewer-note');if(viewerNote){viewerNote.hidden=isForging;viewerNote.textContent='Arrastra para girar · Vista 3D referencial'}
 const resetView=document.querySelector('#reset-view');if(resetView)resetView.hidden=isForging;
 let effects=livePreview.querySelector('.forge-3d-effects');
 if(!effects){const particles=Array.from({length:34},(_,index)=>`<i style="--i:${index};--x:${5+(index*37)%90}%;--y:${8+(index*53)%84}%;--s:${3+(index%5)*1.4}px;--drift:${-34+(index*29)%68}px;--duration:${2.6+(index%6)*.28}s"></i>`).join('');livePreview.insertAdjacentHTML('beforeend',`<div class="forge-3d-effects" aria-hidden="true"><div class="forge-3d-halo"></div><div class="forge-3d-scan"></div><div class="forge-3d-particles">${particles}</div><div class="forge-3d-status"><span></span><div><strong></strong><small></small></div></div></div>`);effects=livePreview.querySelector('.forge-3d-effects')}
 effects.hidden=!isForging;if(isForging){effects.querySelector('strong').textContent=sideImage?'Elaborando tu mockup…':'Preparando el lienzo…';effects.querySelector('small').textContent=sideImage?'Lo revelaremos después de revisar el archivo.':'Tu diseño aparecerá aquí cuando lo cargues.'}
 const panel=document.querySelector('#reference-panel');panel.hidden=true;panel.replaceChildren();
 viewer?.update(renderState);heroViewer?.update(previewState());syncGarmentSamples();
 const fallback=document.querySelector('.preview-fallback img');if(fallback){fallback.hidden=!renderState.image;if(!fallback.hidden)fallback.src=renderState.image}
 if((isForging||showMockup)&&studio.open){if(!viewerPromise)viewerPromise=import('./garment.js').then(async m=>{viewer=await m.createViewer(document.querySelector('#viewer'),renderState);return viewer}).catch(()=>{viewerPromise=null;document.querySelector('.viewer-note').textContent='El visor 3D no está disponible en este navegador.'});
 viewerPromise?.then(()=>{viewer?.update(renderState);viewer?.resize()})}
}
document.querySelectorAll('[data-hero-color]').forEach(b=>b.onclick=()=>{state.color=b.dataset.heroColor;document.querySelectorAll('[data-hero-color]').forEach(s=>s.classList.toggle('chosen',s===b));syncPreview()});
function openStudio(mode='ready',kind){state.mode=mode;if(kind){state.kind=kind;state.size=products[kind].sizes[0]}state.step=1;studio.showModal();document.body.classList.add('locked');renderStep()}
document.querySelectorAll('[data-start]').forEach(button=>button.onclick=()=>openStudio('ready'));
document.querySelectorAll('[data-kind]').forEach(button=>button.onclick=()=>openStudio('ready',button.dataset.kind));
document.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>{button.closest('dialog').close();document.body.classList.remove('locked')});
document.querySelectorAll('dialog').forEach(dialog=>dialog.addEventListener('close',()=>document.body.classList.remove('locked')));
document.querySelector('#space-create').onclick=()=>{document.querySelector('#space').close();openStudio()};
document.querySelector('#reset-view').onclick=()=>viewer?.face(state.printSide);
const sideNames={front:'Frente',back:'Espalda'};
const includedSides=()=>state.printSides;
const hasTwoSides=()=>includedSides().length===2;
const printChoice=()=>hasTwoSides()?'both':state.printSides[0];
const printSidesLabel=()=>includedSides().map(side=>sideNames[side]).join(' + ');
const hasRequiredFiles=()=>includedSides().every(side=>Boolean(state.images[side]));
const failingSides=()=>includedSides().filter(side=>state.assessments[side]&&!state.assessments[side].qualifies);
function activateSide(side){if(!includedSides().includes(side))return;state.printSide=side;state.image=state.images[side]||'';state.assessment=state.assessments[side]||null;state.isDefault=!state.images.front&&!state.images.back}
function faceSelectedSide(){viewer?.face(state.printSide);viewerPromise?.then(()=>viewer?.face(state.printSide))}
function setPrintSides(value){state.printSides=value==='both'?['front','back']:[value];if(!state.printSides.includes(state.printSide))activateSide(state.printSides[0]);state.qualityAccepted=false;state.qualityReview=false}
function removeSide(side){const previous=state.images[side];if(previous?.startsWith('blob:'))URL.revokeObjectURL(previous);state.images[side]='';state.files[side]='';state.assessments[side]=null;state.qualityAccepted=false;state.qualityReview=false;state.uploaded=hasRequiredFiles();activateSide(includedSides()[0]);removeSavedDesignFile(side).catch(()=>{})}
function artworkTone(image){
 const canvas=document.createElement('canvas');canvas.width=canvas.height=48;
 const context=canvas.getContext('2d',{willReadFrequently:true});context.drawImage(image,0,0,48,48);
 const pixels=context.getImageData(0,0,48,48).data;let visible=0,light=0,luminance=0;
 for(let index=0;index<pixels.length;index+=4){
  if(pixels[index+3]<48)continue;
  const value=.2126*pixels[index]+.7152*pixels[index+1]+.0722*pixels[index+2];visible++;luminance+=value;if(value>175)light++;
 }
 return visible&&((light/visible)>.22||luminance/visible>150)?'light':'dark';
}
function printSidesHtml(){
 const selected=hasTwoSides()?'both':state.printSide;
 return `<fieldset class="print-side-picker"><legend>¿Dónde va tu diseño?</legend><div class="print-choice-cards">${[['front','Solo frente','Incluido'],['back','Solo espalda','Incluido'],['both','Ambos',`+${money(PRINT_EXTRAS_CLP.both)}`]].map(([value,label,price])=>`<button type="button" data-print-sides="${value}" class="print-choice ${selected===value?'selected':''}" aria-pressed="${selected===value}"><strong>${label}</strong><span>${price}</span></button>`).join('')}</div></fieldset>`;
}
function uploadCardHtml(side){
 const image=state.images[side];const assessment=state.assessments[side];const checking=state.checking&&state.checkingSide===side;
 const readyLabel=side==='front'?'Frente listo':'Espalda lista';
 const action=checking?'Revisando archivo…':image?`${readyLabel} · Cambiar`:`Cargar ${side==='front'?'frente':'espalda'}`;
 const detail=checking?'Comprobando formato y resolución':image?(assessment?.qualifies?'Archivo cargado':'Archivo cargado · revisaremos su calidad'):'JPG, PNG o WEBP · máx. 50 MB';
 return `<div class="upload-card ${image?'uploaded':''}" data-upload-card="${side}"><label class="dropzone upload-zone" data-drop-side="${side}"><input id="file-${side}" data-file-side="${side}" type="file" accept="image/png,image/jpeg,image/webp"/><span>${image?'<img src="'+image+'" alt="Miniatura del diseño para '+sideNames[side].toLowerCase()+'">':'<svg class="upload-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 16V4m-5 5 5-5 5 5"/><path d="M5 14v5h14v-5"/></svg>'}</span><strong>${action}</strong><small>${detail}</small></label>${image?`<button type="button" class="small-button" data-remove-side="${side}">Quitar archivo</button>`:''}</div>`;
}
const escapeText=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const formatChilePhoneLocal=value=>{let digits=String(value||'').replace(/\D/g,'');if(digits.startsWith('569')&&digits.length>=11)digits=digits.slice(3);else if(digits.startsWith('56')&&digits.length>=10)digits=digits.slice(2).replace(/^9/,'');else if(digits.startsWith('9')&&digits.length===9)digits=digits.slice(1);else if(digits.length>8)digits=digits.slice(-8);return digits.slice(0,8).replace(/^(\d{4})(\d+)/,'$1 $2')};
const fullChilePhone=value=>{const local=formatChilePhoneLocal(value);return local?`+56 9 ${local}`:''};
const phoneFieldHtml=(id,value)=>`<div class="phone-input"><span class="phone-prefix" aria-hidden="true">🇨🇱 <b>+56 9</b></span><input id="${id}" type="tel" required autocomplete="tel" inputmode="numeric" pattern="[0-9]{4} [0-9]{4}" maxlength="9" placeholder="1234 5678" value="${escapeText(formatChilePhoneLocal(value))}"></div>`;
function customReferencesHtml(){
 const items=state.references.map((reference,index)=>`<div class="reference-thumb"><img src="${reference.url}" alt="Referencia ${index+1}"><span title="${escapeText(reference.name)}">${escapeText(reference.name)}</span><button type="button" data-remove-reference="${index}" aria-label="Quitar ${escapeText(reference.name)}">×</button></div>`).join('');
 return `<div class="custom-references"><div class="custom-references-heading"><strong>Fotos de referencia <span>Opcional</span></strong><small>Mascotas, familiares, personas, objetos o estilos que quieras considerar.</small></div><label class="reference-dropzone"><input id="reference-files" type="file" accept="image/png,image/jpeg,image/webp" multiple><span>＋</span><strong>Adjuntar fotos</strong><small>Hasta 6 archivos JPG, PNG o WEBP</small></label>${items?`<div class="reference-thumbs">${items}</div>`:''}</div>`;
}
function fulfillmentDetailsHtml(){
 const date=estimatedDateLabel();
 const contact=state.editingContact?`<div class="fulfillment-contact editing"><label><small>Nombre</small><input id="summary-first-name" required autocomplete="given-name" placeholder="Nombre" value="${escapeText(state.firstName)}"></label><label><small>Apellido</small><input id="summary-last-name" required autocomplete="family-name" placeholder="Apellido" value="${escapeText(state.lastName)}"></label><label><small>Email</small><input id="summary-email" type="email" required autocomplete="email" placeholder="tu@email.com" value="${escapeText(state.email)}"></label><label><small>Teléfono</small>${phoneFieldHtml('summary-phone',state.phone)}</label><button type="button" class="contact-edit-button done" id="finish-contact-edit">Listo</button></div>`:`<div class="fulfillment-contact-summary"><div><span><small>Nombre</small><strong>${escapeText(state.firstName)}</strong></span><span><small>Apellido</small><strong>${escapeText(state.lastName)}</strong></span><span><small>Email</small><strong>${escapeText(state.email)}</strong></span><span><small>Teléfono</small><strong>${escapeText(state.phone)}</strong></span></div><button type="button" class="contact-edit-button" id="edit-contact">Editar</button></div>`;
 if(state.fulfillment==='pickup')return `<section class="fulfillment-details pickup-details">${contact}<span class="eyebrow">RETIRO</span><strong>Retiro coordinado en Providencia</strong><p>Te enviaremos por email la dirección exacta y el horario disponible.</p><div class="estimated-date"><span>Disponible desde</span><b>${date}</b></div></section>`;
 return `<section class="fulfillment-details delivery-details">${contact}<div class="delivery-fields"><label class="field">Región<input id="delivery-region" class="region-search" required autocomplete="address-level1" list="chile-regions" placeholder="Escribe para buscar" value="${escapeText(state.region)}"><datalist id="chile-regions">${chileRegions.map(region=>`<option value="${escapeText(region)}"></option>`).join('')}</datalist></label><label class="field">Comuna<input id="delivery-commune" class="commune-search" required autocomplete="address-level2" list="chile-communes" placeholder="Escribe para buscar" value="${escapeText(state.commune)}"><datalist id="chile-communes">${communesForRegion(state.region).map(commune=>`<option value="${escapeText(commune)}"></option>`).join('')}</datalist></label><label class="field">Dirección<input id="delivery-address" required autocomplete="street-address" placeholder="Calle y número" value="${escapeText(state.address)}"></label><label class="field">Depto., casa u oficina <span>Opcional</span><input id="delivery-address-extra" autocomplete="address-line2" placeholder="Ej. Depto. 304" value="${escapeText(state.addressExtra)}"></label><label class="field delivery-notes-field">Indicaciones de entrega <span>Opcional</span><textarea id="delivery-notes" placeholder="Ej. Llamar al llegar">${escapeText(state.deliveryNotes)}</textarea></label></div><div class="estimated-date"><span>Entrega estimada</span><b>${date}</b></div><small>Si la fecha cae en fin de semana o feriado, se mueve al siguiente día hábil.</small></section>`;
}
function renderStep(){
 const labels=['Detalles','Diseño','Calidad','Resumen','Pago'];
 const railProgress=((state.step-1)/labels.length)*100,railEdge=50/labels.length;
 document.querySelector('.steps').innerHTML=`<div class="steps-rail" style="--rail-progress:${railProgress.toFixed(2)}%;--rail-edge:${railEdge.toFixed(2)}%"><i aria-hidden="true"></i>${labels.map((label,index)=>`<span class="${index+1===state.step?'active':''} ${index+1<state.step?'done':''}" aria-label="Paso ${index+1} de ${labels.length}: ${label}" ${index+1===state.step?'aria-current="step"':''}><b aria-hidden="true">${index+1<state.step?'✓':String(index+1).padStart(2,'0')}</b><small>${label}</small></span>`).join('')}</div>`;
 const p=products[state.kind],choice=printChoice(),pricing=orderTotal(p.price,choice,state.qualityReview?QUALITY_ADJUSTMENT_CLP:0);
 const next=document.querySelector('#next');next.disabled=state.checking;document.querySelector('#back').hidden=state.step===1;
 const ctas=['Siguiente → Sube tu diseño','Revisar y ver mockup','Continuar con revisión','Continuar al pago','Pagar pedido'];next.textContent=ctas[state.step-1];
 let html='';
 if(state.step===1)html=`<span class="eyebrow">PASO 1 · DETALLES</span><h2>Elige tu polera.</h2><section class="detail-block model-block"><div class="detail-heading"><strong>Modelo</strong><small>Precio base</small></div><div class="product-options">${Object.entries(products).map(([id,item])=>`<button type="button" class="${state.kind===id?'selected':''}" data-product="${id}"><strong>${item.name}</strong><span class="model-price">${money(item.price)}</span></button>`).join('')}</div></section><div class="details-grid"><section class="detail-block color-block"><div class="detail-heading"><strong>Color</strong><small>Elige uno</small></div><div class="colors">${[['#ffffff','Blanco'],['#202124','Negro'],['#e8e0cf','Blanco vintage'],['#8daec3','Azul zen']].map(([color,name])=>`<button type="button" aria-label="${name}" title="${name}" data-color="${color}" style="--swatch:${color}" class="${state.color===color?'chosen':''}"></button>`).join('')}</div></section><section class="detail-block size-block"><div class="detail-heading"><strong>Talla</strong><button type="button" class="size-guide-trigger" id="open-size-guide"><span class="size-guide-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M4 16 16 4l4 4L8 20H4v-4Z"/><path d="m13 7 4 4M10 10l2 2M7 13l2 2"/></svg></span><span>Guía de tallas</span><i aria-hidden="true">›</i></button></div><div class="sizes">${p.sizes.map(size=>`<button type="button" data-size="${size}" class="${state.size===size?'selected':''}">${size}</button>`).join('')}</div></section></div><section class="customer-field"><div class="customer-field-heading"><strong>Indícanos tu email</strong><small>Para seguir en contacto.</small></div><label class="field"><span class="sr-only">Email</span><input id="customer-email" type="email" required autocomplete="email" placeholder="tu@email.com" value="${escapeText(state.email)}"></label></section>`;
 if(state.step===2)html=`<span class="eyebrow">PASO 2 · CARGAR DISEÑO</span><h2>¿Dónde lo estampamos?</h2>${printSidesHtml()}<div class="upload-grid ${hasTwoSides()?'two-sides':''}">${includedSides().map(uploadCardHtml).join('')}</div><p class="field-note">Verás una miniatura apenas cargues el archivo. La calidad se revisa en el siguiente paso.</p><section class="customer-field customer-name"><div class="customer-field-heading"><strong>Indícanos tus datos</strong><small>Para personalizar tu experiencia y coordinar tu pedido.</small></div><div class="customer-name-fields"><label class="field"><span>Nombre</span><input id="customer-first-name" required autocomplete="given-name" placeholder="Nombre" value="${escapeText(state.firstName)}"></label><label class="field"><span>Apellido</span><input id="customer-last-name" required autocomplete="family-name" placeholder="Apellido" value="${escapeText(state.lastName)}"></label><label class="field customer-phone-field"><span>Teléfono</span>${phoneFieldHtml('customer-phone',state.phone)}</label></div></section>`;
 if(state.step===3){const names=failingSides().map(side=>sideNames[side].toLowerCase()).join(' y ');html=`<span class="eyebrow">PASO 3 · REVISIÓN</span><h2>Tu diseño necesita un ajuste.</h2><div class="quality-warning" role="alert"><strong>Podría verse pixelado al imprimir.</strong><p>El archivo de ${names} no alcanza ${PRINT_POLICY.minPpi} ppp. Lo revisaremos amablemente con nuestro equipo antes de producirlo.</p><div class="quality-cost"><span>Ajuste técnico adicional</span><strong>+${money(QUALITY_ADJUSTMENT_CLP)}</strong></div><div class="quality-actions"><button type="button" class="small-button" id="replace-low">Subir otro archivo</button><button type="button" class="button dark" id="accept-review">Continuar con revisión · +${money(QUALITY_ADJUSTMENT_CLP)}</button></div></div>`}
 if(state.step===4)html=`<span class="eyebrow">PASO 4 · RESUMEN</span><h2>Tu idea, lista para pedir.</h2>${hasTwoSides()?`<div class="mockup-sides">${includedSides().map(side=>`<button type="button" data-view-side="${side}" class="${state.printSide===side?'selected':''}">${sideNames[side]}</button>`).join('')}</div>`:''}<p class="mockup-note">Gira la polera, revisa los detalles y confirma tu pedido.</p>${state.qualityReview?`<div class="review-chip">Revisión del equipo incluida · ${money(QUALITY_ADJUSTMENT_CLP)}</div>`:''}<div class="order-summary"><div><span>Polera ${p.name} · talla ${state.size}</span><strong>${money(pricing.base)}</strong></div><div><span>Diseño ${printSidesLabel()}</span><strong>${pricing.print?`+${money(pricing.print)}`:'Incluido'}</strong></div>${state.qualityReview?`<div><span>Ajuste técnico del archivo</span><strong>+${money(QUALITY_ADJUSTMENT_CLP)}</strong></div>`:''}<div><span>Extras</span><strong>${money(0)}</strong></div><div class="total"><span>Total</span><strong>${money(pricing.total)}</strong></div></div><fieldset class="fulfillment-picker"><legend>¿Cómo quieres recibirla?</legend><div class="fulfillment-options"><button type="button" data-fulfillment="delivery" class="fulfillment-choice ${state.fulfillment==='delivery'?'selected':''}" aria-pressed="${state.fulfillment==='delivery'}"><span class="fulfillment-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M3 6h11v11H3zM14 10h4l3 3v4h-7zM7 20a2 2 0 1 0 0-4 2 2 0 0 0 0 4Zm10 0a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z"/></svg></span><span><strong>Despacho</strong><small>Calculamos el valor con tu dirección</small></span><b>Por calcular</b></button><button type="button" data-fulfillment="pickup" class="fulfillment-choice ${state.fulfillment==='pickup'?'selected':''}" aria-pressed="${state.fulfillment==='pickup'}"><span class="fulfillment-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M12 21s7-6.1 7-12a7 7 0 1 0-14 0c0 5.9 7 12 7 12Z"/><circle cx="12" cy="9" r="2.5"/></svg></span><span><strong>Retiro</strong><small>Coordinamos contigo el punto y horario</small></span><b>Gratis</b></button></div></fieldset>${fulfillmentDetailsHtml()}`;
 if(state.step===5)html=`<span class="eyebrow">PASO 5 · PAGO</span><h2>Confirma y paga.</h2><div class="checkout-fulfillment"><span>${state.fulfillment==='delivery'?'Despacho a domicilio':'Retiro coordinado'}</span><button type="button" id="change-fulfillment">Cambiar</button></div><div class="checkout-customer"><span><small>Nombre</small><strong>${escapeText(state.name)}</strong></span>${state.fulfillment==='delivery'?`<span><small>Teléfono</small><strong>${escapeText(state.phone)}</strong></span><span><small>Entrega</small><strong>${escapeText(state.address)}${state.addressExtra?`, ${escapeText(state.addressExtra)}`:''}, ${escapeText(state.commune)}, ${escapeText(state.region)}</strong></span>`:`<span><small>Retiro</small><strong>Providencia · desde ${estimatedDateLabel()}</strong></span>`}</div><label class="checkout-email-confirm">Confirma tu email<input id="checkout-email" type="email" required autocomplete="email" value="${escapeText(state.email)}"><small>Este será el correo asociado a la compra y a sus actualizaciones.</small></label><div class="checkout-total"><span>${state.fulfillment==='delivery'?'Subtotal · despacho por calcular':'Total del pedido'}</span><strong>${money(pricing.total)}</strong></div><div class="notice">Checkout de demostración: no se realizará ningún cobro.</div>`;
 document.querySelector('#step-content').innerHTML=html;
 if(state.step===4){const cartAdd=document.createElement('button');cartAdd.type='button';cartAdd.id='add-to-cart';cartAdd.className='add-to-cart';cartAdd.innerHTML='Guardar en mi carro <span>Bag</span>';document.querySelector('.order-summary')?.after(cartAdd);cartAdd.onclick=()=>addCurrentToCart()}
 ['customer-email','customer-first-name','customer-last-name','customer-phone','summary-email','summary-first-name','summary-last-name','summary-phone','checkout-email'].forEach(id=>{const input=document.querySelector(`#${id}`);if(!input)return;if(!input.placeholder)input.placeholder='tu@email.com';const wrapper=document.createElement('div');wrapper.className='clearable-input';input.before(wrapper);wrapper.append(input);const clear=document.createElement('button');clear.type='button';clear.className='clear-input';clear.setAttribute('aria-label',`Borrar ${id.includes('phone')?'teléfono':id.includes('last-name')?'apellido':id.includes('name')?'nombre':'email'}`);clear.innerHTML='<span aria-hidden="true"></span>';clear.onclick=()=>{input.value='';input.dispatchEvent(new Event('input',{bubbles:true}));input.focus()};wrapper.append(clear)});
 document.querySelectorAll('[data-print-sides]').forEach(b=>b.onclick=()=>{setPrintSides(b.dataset.printSides);renderStep();faceSelectedSide()});
 document.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>{state.kind=b.dataset.product;if(!products[state.kind].sizes.includes(state.size))state.size=products[state.kind].sizes[0];renderStep()});
 document.querySelectorAll('[data-size]').forEach(b=>b.onclick=()=>{state.size=b.dataset.size;renderStep()});
 document.querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>{state.color=b.dataset.color;renderStep()});
 const guide=document.querySelector('#size-guide-modal');const openGuide=document.querySelector('#open-size-guide');if(openGuide)openGuide.onclick=()=>guide.showModal();
 guide.querySelectorAll('[data-size-close]').forEach(button=>button.onclick=()=>guide.close());
 guide.querySelectorAll('[data-guide-size]').forEach(button=>button.onclick=()=>{state.size=button.dataset.guideSize;guide.close();renderStep();toast(`Talla ${state.size} seleccionada.`)});
 document.querySelectorAll('[data-view-side]').forEach(b=>b.onclick=()=>{activateSide(b.dataset.viewSide);renderStep();faceSelectedSide()});
 document.querySelectorAll('[data-remove-side]').forEach(b=>b.onclick=()=>{removeSide(b.dataset.removeSide);renderStep();toast('Archivo eliminado.')});
 document.querySelectorAll('[data-file-side]').forEach(file=>{const side=file.dataset.fileSide;file.onchange=()=>upload(file.files[0],side);const drop=file.closest('.dropzone');drop.ondragover=e=>{e.preventDefault();drop.classList.add('dragging')};drop.ondragleave=()=>drop.classList.remove('dragging');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('dragging');upload(e.dataTransfer.files[0],side)}})
 const replace=document.querySelector('#replace-low');if(replace)replace.onclick=()=>{state.step=2;renderStep();setTimeout(()=>document.querySelector(`[data-file-side="${failingSides()[0]||state.printSide}"]`)?.click())};
 const accept=document.querySelector('#accept-review');if(accept)accept.onclick=()=>{state.qualityAccepted=true;state.qualityReview=true;state.step=4;renderStep();faceSelectedSide()};
 const email=document.querySelector('#customer-email');if(email)email.oninput=()=>{state.email=email.value.trim();storeCustomerDetails()};
 const firstName=document.querySelector('#customer-first-name');if(firstName)firstName.oninput=()=>{state.firstName=firstName.value;storeCustomerDetails()};
 const lastName=document.querySelector('#customer-last-name');if(lastName)lastName.oninput=()=>{state.lastName=lastName.value;storeCustomerDetails()};
 const customerPhone=document.querySelector('#customer-phone');if(customerPhone)customerPhone.oninput=()=>{customerPhone.value=formatChilePhoneLocal(customerPhone.value);state.phone=fullChilePhone(customerPhone.value);storeCustomerDetails()};
 const address=document.querySelector('#delivery-address');if(address)address.oninput=()=>{state.address=address.value;storeCustomerDetails()};
 const commune=document.querySelector('#delivery-commune');if(commune)commune.oninput=()=>{commune.setCustomValidity('');state.commune=commune.value;storeCustomerDetails()};
 const region=document.querySelector('#delivery-region');if(region)region.oninput=()=>{region.setCustomValidity('');state.region=region.value;const allowed=communesForRegion(region.value),communeList=document.querySelector('#chile-communes');if(communeList)communeList.innerHTML=allowed.map(commune=>`<option value="${escapeText(commune)}"></option>`).join('');if(commune&&commune.value&&!allowed.some(item=>samePlace(item,commune.value))){commune.value='';state.commune=''}storeCustomerDetails()};
 const addressExtra=document.querySelector('#delivery-address-extra');if(addressExtra)addressExtra.oninput=()=>{state.addressExtra=addressExtra.value;storeCustomerDetails()};
 const deliveryNotes=document.querySelector('#delivery-notes');if(deliveryNotes)deliveryNotes.oninput=()=>{state.deliveryNotes=deliveryNotes.value;storeCustomerDetails()};
 const summaryFirstName=document.querySelector('#summary-first-name');if(summaryFirstName)summaryFirstName.oninput=()=>{state.firstName=summaryFirstName.value;storeCustomerDetails()};
 const summaryLastName=document.querySelector('#summary-last-name');if(summaryLastName)summaryLastName.oninput=()=>{state.lastName=summaryLastName.value;storeCustomerDetails()};
 const summaryEmail=document.querySelector('#summary-email');if(summaryEmail)summaryEmail.oninput=()=>{state.email=summaryEmail.value.trim();storeCustomerDetails()};
 const summaryPhone=document.querySelector('#summary-phone');if(summaryPhone)summaryPhone.oninput=()=>{summaryPhone.value=formatChilePhoneLocal(summaryPhone.value);state.phone=fullChilePhone(summaryPhone.value);storeCustomerDetails()};
 const editContact=document.querySelector('#edit-contact');if(editContact)editContact.onclick=()=>{state.editingContact=true;renderStep()};
 const finishContactEdit=document.querySelector('#finish-contact-edit');if(finishContactEdit)finishContactEdit.onclick=()=>{const fields=[document.querySelector('#summary-first-name'),document.querySelector('#summary-last-name'),document.querySelector('#summary-email'),document.querySelector('#summary-phone')];for(const field of fields)if(!field?.checkValidity())return field?.reportValidity();state.firstName=fields[0].value.trim();state.lastName=fields[1].value.trim();state.email=fields[2].value.trim();state.phone=fullChilePhone(fields[3].value);storeCustomerDetails();state.editingContact=false;renderStep()};
 const checkoutEmail=document.querySelector('#checkout-email');if(checkoutEmail)checkoutEmail.oninput=()=>{state.email=checkoutEmail.value.trim();storeCustomerDetails()};
 document.querySelectorAll('[data-fulfillment]').forEach(button=>button.onclick=()=>{state.fulfillment=button.dataset.fulfillment;persistDraft();renderStep()});
 const changeFulfillment=document.querySelector('#change-fulfillment');if(changeFulfillment)changeFulfillment.onclick=()=>{state.step=4;renderStep()};
 syncScaleControl();syncPreview();
 normalizeTextSymbols(document.querySelector('#step-content')||document);
}
function addReferenceFiles(fileList){
 const available=Math.max(0,6-state.references.length);const incoming=[...(fileList||[])];
 if(!available)return toast('Puedes adjuntar hasta 6 fotos de referencia.');
 const compatible=incoming.filter(file=>['image/png','image/jpeg','image/webp'].includes(file.type)&&file.size<=PRINT_POLICY.maxBytes).slice(0,available);
 compatible.forEach(file=>state.references.push({name:file.name,url:URL.createObjectURL(file)}));
 renderStep();
 if(!compatible.length)return toast('Elige fotos JPG, PNG o WEBP de hasta 50 MB.');
 if(compatible.length<incoming.length)toast(`Adjuntamos ${compatible.length} foto${compatible.length===1?'':'s'}. Algunas no eran compatibles o superaban el límite.`);
 else toast(`${compatible.length} foto${compatible.length===1?' adjunta':'s adjuntas'} como referencia opcional.`);
}
async function upload(file,side=state.printSide){
 if(!file)return;
 if(!['image/png','image/jpeg','image/webp'].includes(file.type))return toast('Formato no compatible. Elige JPG, PNG o WEBP.');
 if(file.size>PRINT_POLICY.maxBytes)return toast('El archivo supera los 50 MB. Reduce su peso y vuelve a subirlo.');
 const token=++uploadVersions[side],url=URL.createObjectURL(file);state.checking=true;state.checkingSide=side;activateSide(side);renderStep();viewer?.face(side);
 try{
  const img=new Image();img.src=url;await img.decode();if(token!==uploadVersions[side]){URL.revokeObjectURL(url);return}
  const previous=state.images[side];if(previous?.startsWith('blob:'))URL.revokeObjectURL(previous);
  state.images[side]=url;state.files[side]=file.name;activateSide(side);state.uploaded=hasRequiredFiles();state.file=file.name;state.artworkTone=artworkTone(img);state.assessment=checkResolution(img.naturalWidth,img.naturalHeight);state.assessments[side]=state.assessment;state.checking=false;state.checkingSide='';state.qualityAccepted=false;state.qualityReview=false;saveDesignFile(side,file).catch(()=>toast('El diseño se cargó, pero este navegador no pudo guardarlo para después.'));renderStep();faceSelectedSide();if(!state.assessment.qualifies)toast('Archivo cargado. Te explicaremos la revisión antes de avanzar.')
 }catch{URL.revokeObjectURL(url);if(token===uploadVersions[side]){state.checking=false;state.checkingSide='';renderStep();toast('El archivo no se pudo leer. Prueba con otra imagen.')}}}
async function restoreSavedDesigns(){try{const saved=await savedDesignFiles();for(const item of saved){if(item.expiresAt<=Date.now()){removeSavedDesignFile(item.side).catch(()=>{});continue}if(!['front','back'].includes(item.side)||!(item.file instanceof Blob))continue;const url=URL.createObjectURL(item.file);const image=new Image();image.src=url;try{await image.decode()}catch{URL.revokeObjectURL(url);removeSavedDesignFile(item.side).catch(()=>{});continue}state.images[item.side]=url;state.files[item.side]=item.file.name||'Diseño guardado';state.assessments[item.side]=checkResolution(image.naturalWidth,image.naturalHeight);state.artworkTone=artworkTone(image)}state.uploaded=hasRequiredFiles();activateSide(includedSides()[0]);syncPreview();if(studio.open)renderStep()}catch{}}
function persistDraft(){syncFullName();try{saveForFifteenDays(DRAFT_KEY,{kind:state.kind,size:state.size,color:state.color,printSides:state.printSides,qualityReview:state.qualityReview,fulfillment:state.fulfillment,date:new Date().toISOString()})}catch{toast('No pudimos guardar el avance en este navegador.')}}
document.querySelector('#back').onclick=()=>{state.step=state.step===4&&!failingSides().length?2:Math.max(1,state.step-1);renderStep()};
document.querySelector('#design-form').onsubmit=e=>{
 e.preventDefault();if(state.checking)return;
 if(state.step===1){const email=document.querySelector('#customer-email');if(!email?.checkValidity())return email?.reportValidity();state.email=email.value.trim();storeCustomerDetails();state.step=2;return renderStep()}
 if(state.step===2){const firstName=document.querySelector('#customer-first-name'),lastName=document.querySelector('#customer-last-name'),phone=document.querySelector('#customer-phone');if(!firstName?.checkValidity())return firstName?.reportValidity();if(!lastName?.checkValidity())return lastName?.reportValidity();if(!phone?.checkValidity())return phone?.reportValidity();state.firstName=firstName.value.trim();state.lastName=lastName.value.trim();state.phone=fullChilePhone(phone.value);storeCustomerDetails();if(!hasRequiredFiles()){const missing=includedSides().filter(side=>!state.images[side]).map(side=>sideNames[side].toLowerCase()).join(' y ');return toast(`Carga el archivo de ${missing} para continuar.`)}state.step=failingSides().length?3:4;activateSide(includedSides()[0]);return renderStep()}
 if(state.step===3){state.qualityAccepted=true;state.qualityReview=true;state.step=4;return renderStep()}
 if(state.step===4){const summaryFirstName=document.querySelector('#summary-first-name'),summaryLastName=document.querySelector('#summary-last-name'),summaryEmail=document.querySelector('#summary-email'),summaryPhone=document.querySelector('#summary-phone');if(state.editingContact){for(const field of [summaryFirstName,summaryLastName,summaryEmail,summaryPhone])if(!field?.checkValidity())return field?.reportValidity();state.firstName=summaryFirstName.value.trim();state.lastName=summaryLastName.value.trim();state.email=summaryEmail.value.trim();state.phone=fullChilePhone(summaryPhone.value)}if(state.fulfillment==='delivery'){const fields=['delivery-region','delivery-address','delivery-commune'].map(id=>document.querySelector(`#${id}`));for(const field of fields)if(!field?.checkValidity())return field?.reportValidity();const matchedRegion=chileRegions.find(region=>samePlace(region,fields[0].value.trim()));if(!matchedRegion){fields[0].setCustomValidity('Selecciona una región de la lista.');return fields[0].reportValidity()}const matchedCommune=communesForRegion(matchedRegion).find(commune=>samePlace(commune,fields[2].value.trim()));if(!matchedCommune){fields[2].setCustomValidity('Selecciona una comuna de la lista.');return fields[2].reportValidity()}state.region=matchedRegion;state.address=fields[1].value.trim();state.commune=matchedCommune;state.addressExtra=document.querySelector('#delivery-address-extra')?.value.trim()||'';state.deliveryNotes=document.querySelector('#delivery-notes')?.value.trim()||''}storeCustomerDetails();persistDraft();state.editingContact=false;state.step=5;return renderStep()}
 const checkoutEmail=document.querySelector('#checkout-email');if(!checkoutEmail?.checkValidity())return checkoutEmail?.reportValidity();state.email=checkoutEmail.value.trim();storeCustomerDetails();state.checkoutReady=true;persistDraft();toast('Checkout de demostración listo. No se realizó ningún cobro.')
};
function showSaved(){}
let toastTimer;function toast(message){const el=document.querySelector('#toast');(document.querySelector('dialog[open]')||document.body).append(el);el.textContent=message;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),4500)}
normalizeTextSymbols();
restoreSavedDesigns();

// Las poleras acompañan levemente el scroll para dar profundidad sin distraer.
const reduceShirtMotion=window.matchMedia('(prefers-reduced-motion: reduce)');
let shirtMotionFrame=0;
function updateShirtMotion(){
 shirtMotionFrame=0;
 if(reduceShirtMotion.matches)return;
 const viewportHeight=window.innerHeight||1;
 document.querySelectorAll('#hero-viewer,.garment-viewer,.custom-shirt-image').forEach((element,index)=>{
  const box=element.getBoundingClientRect();
  const distance=(box.top+box.height/2-viewportHeight/2)/viewportHeight;
  const direction=index%2===0?1:-1;
  const turn=Math.max(-.22,Math.min(.22,distance*.34*direction));
  if(element.id==='hero-viewer')heroViewer?.turn(turn);
  else if(element.classList.contains('garment-viewer')){
   const kind=element.closest('.garment')?.dataset.kind;
   garmentViewers.get(kind)?.turn(turn);
  }else element.style.setProperty('--shirt-turn',`${(turn*57.2958).toFixed(2)}deg`);
 });
}
function requestShirtMotion(){
 if(!shirtMotionFrame)shirtMotionFrame=requestAnimationFrame(updateShirtMotion);
}
window.addEventListener('scroll',requestShirtMotion,{passive:true});
window.addEventListener('resize',requestShirtMotion,{passive:true});
reduceShirtMotion.addEventListener?.('change',requestShirtMotion);
requestShirtMotion();

const revealSite=async()=>{
 const preloader=document.querySelector('#site-preloader');
 const app=document.querySelector('#app');
 if(!preloader){app?.removeAttribute('aria-busy');return}
 const started=performance.now();
 const pageLoaded=document.readyState==='complete'?Promise.resolve():new Promise(resolve=>window.addEventListener('load',resolve,{once:true}));
 const fontsLoaded=document.fonts?.ready||Promise.resolve();
 await Promise.race([Promise.allSettled([pageLoaded,fontsLoaded]),new Promise(resolve=>setTimeout(resolve,3500))]);
 const remaining=Math.max(0,520-(performance.now()-started));
 if(remaining)await new Promise(resolve=>setTimeout(resolve,remaining));
 requestAnimationFrame(()=>{
  preloader.classList.add('is-leaving');
  document.body.classList.remove('is-preloading');
  app?.setAttribute('aria-busy','false');
  setTimeout(()=>preloader.remove(),380);
 });
};
revealSite();
