import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
export async function createViewer(container,state){
 const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(35,1,.1,100);camera.position.set(0,0,6.8);const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(container.clientWidth,container.clientHeight);container.replaceChildren(renderer.domElement);renderer.domElement.setAttribute('aria-label','Polera 3D: arrastra para girar y usa la rueda para acercar');
 scene.add(new THREE.HemisphereLight(0xffffff,0x8b8397,3));const light=new THREE.DirectionalLight(0xffffff,4);light.position.set(-3,4,6);scene.add(light);const controls=new OrbitControls(camera,renderer.domElement);controls.enablePan=false;controls.enableDamping=true;controls.minDistance=4;controls.maxDistance=9;controls.minPolarAngle=Math.PI*.22;controls.maxPolarAngle=Math.PI*.78;
 const group=new THREE.Group();scene.add(group);const shape=new THREE.Shape();shape.moveTo(-.38,1.24);shape.quadraticCurveTo(0,.87,.38,1.24);shape.lineTo(.74,1.15);shape.lineTo(1.27,.7);shape.lineTo(.94,.28);shape.lineTo(.65,.5);shape.lineTo(.65,-1.15);shape.quadraticCurveTo(0,-1.23,-.65,-1.15);shape.lineTo(-.65,.5);shape.lineTo(-.94,.28);shape.lineTo(-1.27,.7);shape.lineTo(-.74,1.15);shape.closePath();
 const geometry=new THREE.ExtrudeGeometry(shape,{depth:.14,bevelEnabled:true,bevelSegments:4,steps:1,bevelSize:.06,bevelThickness:.065,curveSegments:32});geometry.translate(0,0,-.07);const material=new THREE.MeshStandardMaterial({color:state.color,roughness:.92});const shirt=new THREE.Mesh(geometry,material);group.add(shirt);
 const printMaterial=new THREE.MeshStandardMaterial({transparent:true,roughness:.9,side:THREE.FrontSide,polygonOffset:true,polygonOffsetFactor:-1});const print=new THREE.Mesh(new THREE.PlaneGeometry(.87,1),printMaterial);print.position.set(0,.04,.139);group.add(print);let currentImage='',generation=0;
 async function update(s){material.color.set(s.color);group.scale.set(s.kind==='over'?1.13:s.kind==='kids'?.83:1,s.kind==='kids'?.88:1,1);if(currentImage!==s.image){currentImage=s.image;const token=++generation;const texture=await new THREE.TextureLoader().loadAsync(s.image);if(token!==generation){texture.dispose();return}texture.colorSpace=THREE.SRGBColorSpace;const aspect=texture.image.width/texture.image.height;print.scale.set(aspect> .87?1:aspect/.87,aspect>.87?.87/aspect:1,1);printMaterial.map?.dispose();printMaterial.map=texture;printMaterial.needsUpdate=true}}
 function resize(){const w=container.clientWidth,h=container.clientHeight;if(!w||!h)return;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h)}new ResizeObserver(resize).observe(container);renderer.setAnimationLoop(()=>{if(!container.closest('dialog')?.open)return;controls.update();renderer.render(scene,camera)});await update(state);resize();return{update,resize,reset(){camera.position.set(0,0,6.8);controls.target.set(0,0,0);controls.update()}};
}
